# One may have a look at http://docs.travis-ci.com/user/installing-dependencies/

language: c
cache: ccache
git:
  depth: 1

before_install:
  # Install the arm32 cross-compiler
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-linux-gnueabihf
  - arm-linux-gnueabihf-gcc --version
  # Install bc (required by the kernel)
  - sudo apt-get install bc
  # Install 32-bit compatibility libraries for the Linaro arm64 cross-compiler
  # (which is a 32-bit x86 binary)
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install libc6-i386 lib32stdc++6 lib32z1; fi
  - sudo apt-get install u-boot-tools lzop
before_script:
  # Store the home repository
 
  - export MYHOME=$PWD


script:


  - export PATH=/usr/lib/ccache:$PATH

  # arm32 compilation
  - export ARCH=arm
  - export CROSS_COMPILE=arm-linux-gnueabihf-
 
  #add my modules

  - make sun7i_defconfig
  - make -j`getconf _NPROCESSORS_ONLN` uImage modules
# - make -j`getconf _NPROCESSORS_ONLN` M=$MYHOME modules



