# One may have a look at http://docs.travis-ci.com/user/installing-dependencies/

language: c

git:
  depth: 1
  
notifications:
  - email: true
env:
  global:
    # Git and Github credentials for pushing documentation
    #- GIT_NAME=poppy-bot
    #- GIT_EMAIL=poppy-bot-ci@inria.fr
    # GH_TOKEN encrypted below > travis encrypt GH_TOKEN=XXXXXX --add
    # You have to overwrite your hown token to push the documentation to your repo.
    #- secure: ""
before_install:
  # Install the arm32 cross-compiler
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-linux-gnueabihf
  - arm-linux-gnueabihf-gcc --version
  # Install bc (required by the kernel)
  - sudo apt-get install bc
  # Install 32-bit compatibility libraries for the Linaro arm64 cross-compiler
  # (which is a 32-bit x86 binary)
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install libc6-i386 lib32stdc++6 lib32z1; fi
  - sudo apt-get install u-boot-tools lzop
before_script:
  # Store the home repository
  - export MYHOME=$PWD


script:




  # arm32 compilation
  - export ARCH=arm
  - export CROSS_COMPILE=arm-linux-gnueabihf-
  #- echo "CONFIG_MODULES=y" >> arch/arm/configs/multi_v7_defconfig
  #add my modules
  - echo "CONFIG_PWM=y" >> arch/arm/configs/sun7i_defconfig
  - echo "CONFIG_PWM_SYSFS=y" >> arch/arm/configs/sun7i_defconfig
  - echo "CONFIG_PWM_SUN4I=m" >> arch/arm/configs/sun7i_defconfig
  - echo "CONFIG_LIRC_SEND_PWM=m" >> arch/arm/configs/sun7i_defconfig
  - make sun7i_defconfig
  - make -j`getconf _NPROCESSORS_ONLN` uImage modules
# - make -j`getconf _NPROCESSORS_ONLN` M=$MYHOME modules


after_success:
 - make deb-pkg
 
- git config --global user.name $GIT_NAME
- git config --global user.email $GIT_EMAIL

